# Permalinks
permalink:        pretty

# Setup
title:            '@idnan_se'
tagline:          Ramblings of a full-stack web developer
url:              https://www.adnanahmed.info
enforce_ssl:      www.adnanahmed.info
paginate:         1
baseurl:          /
author:
  name:           Adnan Ahmed
  url:            https://adnanahmed.info
  email:          idnan.se@gmail.com
  description:	  'I am Adnan Ahmed, a full stack web developer.'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/idnan/idnan.github.io

# Menu
pages_list:       
  Archive: '/archive'
  About: '/about'
  Feed: '/atom.xml'

# Stay in touch
external_links:
  'github.com/idnan': 'http://github.com/idnan'
  'idnan.se@gmail.com': 'mailto:idnan.se@gmail.com'
  'linkedin.com/in/adnaanahmed': 'http://www.linkedin.com/in/adnaanahmed'
