# Permalinks
permalink:        pretty

# Setup
title:            '@idnan_se'
tagline:          Lead engineer at tajawal. Lover of all things web, ponderer of new technology, fanatic of simplicity, OSS enthusiast
url:              http://adnanahmed.info
enforce_ssl:      www.adnanahmed.info
paginate:         1
baseurl:          /
author:
  name:           Adnan Ahmed
  url:            http://adnanahmed.info
  email:          idnan.se@gmail.com
  description:	  'Lead engineer at tajawal. Lover of all things web, ponderer of new technology, fanatic of simplicity, OSS enthusiast'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/idnan/idnan.github.io

# Menu
pages_list:       
  Archive: '/archive'
  About: '/about'
  Feed: '/atom.xml'

# Stay in touch
external_links:
  'github.com/idnan': 'http://github.com/idnan'
  'idnan.se@gmail.com': 'mailto:idnan.se@gmail.com'
  'linkedin.com/in/adnaanahmed': 'http://www.linkedin.com/in/adnaanahmed'
