title: Adnan Ahmed
description: "Lead engineer at tradeling. Lover of all things web, ponderer of new technology, fanatic of simplicity, OSS enthusiast"
url: "http://adnanahmed.info"
author: "Adnan Ahmed"
keywords: "adnan,idnan_se,adnan ahmed,idnan,code,javascript,php,databases,elasticsearch,startups,react,angular,javascript,elk,kibana"
github: idnan
medium: idnan
twitter: idnan_se
email: idnan.se@gmail.com

exclude: ["README.md", "CNAME", "LICENSE", ".gitignore"]

permalink: pretty
timezone: Asia/Abu_Dhabi

plugins: ["jekyll-sitemap"]

defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "base"
