baseURL = "https://adnanahmed.info/"
title = "Adnan Ahmed"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = "adnanahmed.info"
googleAnalytics = "UA-56161851-1"

Paginate = 20
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Engineer, Designer, Explorer, Opensourcerer, Educator, Lifelong Learner, Lead Engineer @tajawalae Available for Freelance Work"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css", "css/highlight.github.css"]
customJS = ["js/custom.js", "js/highlight.pack.js", "js/highlight-trigger.js"]
gopher = "https://gopherize.me/gopher/b26e272ca70278cf6cc1ce8d5da0f793c56193c0" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Adnan Ahmed"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "2006-01"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = false

[params.widgets]
homepage = ["recent_posts"]
footer = ["social_menu"]

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "idnan.se@gmail.com"
github = "idnan"
instagram = "idnan.ahmed"
linkedin = "adnaanahmed"
twitter = "idnan_se"

[params.comments]
enable = true

[params.search]
client = "" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Posts"
url = "/posts"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1